### ISSUE TITLE
java.io.EOFException: Input closed at net.sf.expectit.SingleInputExpect.expect(SingleInputExpect.java:171)

### ISSUE THREAD

**Issue by hozhanli** [Alexey1Gavrilov/ExpectIt#54]
When multiple time connect to a device I get this exception. Stack trace is:

java.io.EOFException: Input closed
	at net.sf.expectit.SingleInputExpect.expect(SingleInputExpect.java:171) ~[expectit-core-0.8.3.jar!/:na]
	at net.sf.expectit.ExpectImpl.expectIn(ExpectImpl.java:103) ~[expectit-core-0.8.3.jar!/:na]
	at net.sf.expectit.AbstractExpectImpl.expectIn(AbstractExpectImpl.java:57) ~[expectit-core-0.8.3.jar!/:na]
	at net.sf.expectit.AbstractExpectImpl.expect(AbstractExpectImpl.java:61) ~[expectit-core-0.8.3.jar!/:na]
	at com.coodehub.service.machine.MachineServiceImpl.huaweiSsh(MachineServiceImpl.java:449) ~[classes!/:0.0.1-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_171]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) ~[spring-context-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_171]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_171]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]

**Comment by agavrilov76** [comment]
There is not enough information to analyse this issue. Provide some code examples. 
EOFException can be thrown if the connection has been closed on the remote side.
